export const SUCCESSFUL_AUTHENTICATION = 'USER/SUCCESSFUL_AUTHENTICATION';
export const CLEAR_AUTHENTICATION = 'USER/CLEAR_AUTHENTICATION';
export const SET_AUTHENTICATION_USER = 'USER/SET_AUTHENTICATION_USER';
export const SET_ERROR_AUTHENTICATED = 'USER/SET_ERROR_AUTHENTICATED';